name: Update repo

on:
  schedule:
    - cron:  '0,30 0-23 * * *'

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      run: |
        git clone https://github.com/pkgs-termux/x11-packages.git
        mv x11-packages x11-packages-pacman
    - name: Clone root repository
      run: git clone https://github.com/termux/x11-packages.git
    - name: Update repo
      run: |
        # Edit
        cd x11-packages-pacman
        rm -fr */
        cd ../x11-packages
        cp -r * ../x11-packages-pacman
        # Get list pkg
        cd ../x11-packages-pacman
        list_files=""
        for i in $(git status -s packages | awk '{print $2}'); do
          dir_sp=(${i//// })
          if [[ ! $(echo "$list_files" | grep "/${dir_sp[1]} ") ]]; then
            list_files+="packages/${dir_sp[1]} "
          fi
        done
        list_files=($list_files)
        # Sort list pkg
        cd ../x11-packages
        list_sort=""
        for i in ${list_files[@]}; do
          list_sort+="$(git rev-list --count "$(git log -n 1 --pretty=format:%H -- $i)") "
        done
        list_sort=($list_sort)
        copy_list_sort=($(sort -n <(printf "%s\n" "${list_sort[@]}")))
        search_index() {
          for i in "${!list_sort[@]}"; do
            if [[ "${list_sort[$i]}" = "${1}" ]]; then
              echo "${i}";
            fi
          done
        }
        sort_list_files=""
        for i in ${copy_list_sort[@]}; do
          e=1
          while :; do
            index=$(search_index "$i" | sed -n "${e}p")
            if [[ $(echo "$sort_list_files " | grep "${list_files[$index]} ") ]]; then
              e=$(($e+1))
            else
              break
            fi
          done
          if (( $e == 1 )); then
            sort_list_files+=" "
          else
            sort_list_files+="&&"
          fi
          sort_list_files+="${list_files[$index]}"
        done
        # Start upload
        cd ../x11-packages-pacman
        info() {
          echo "==> $1"
        }
        commet() {
          echo "-> $1"
        }
        git config --global user.name "termux-actions[bot]"
        git config --global user.email "termux-actions[bot]@users.noreply.github.com"
        git remote set-url origin "https://Maxython:${{ secrets.TOKEN }}@github.com/pkgs-termux/x11-packages.git"
        info "Update system repo"
        git add .
        git reset packages
        {
          git commit -m "Update repo"
          git push origin master
        } || true
        info "Update repo packages"
        for i in $sort_list_files; do
          commet "${i}"
          git add $(echo $i | sed 's/&&/ /g')
          git commit -m "${i}"
          git push origin master
        done
